In [32]:
# Pandas Assignment
''' Start by loading the IRIS dataset.
A. Display the following information:
i. first 10 rows
ii. shape and datatypes
iii. summary statistics(mean, std, min, max)
'''

import pandas as pd
df=pd.read_csv("IRIS.csv")
df.head(10)
df.shape
df.dtypes

df[["sepal_length", "sepal_width", "petal_length", "petal_width"]].agg(
    ["mean", "std", "min", "max"]
)


'''select only those rows where:
i. petal_length> 4.5
ii. species="Iris-virginica"
'''

result=df[(df["petal_length"]> 4.5) & (df["species"]=="Iris-virginica")]
result, result.shape



'''Group by species and compute
i. average sepal_length
ii. maxinum petal_width
iii. standard deviation of sepal_width
'''

group_result=df.groupby("species").agg(
    avg_sepal_length=("sepal_length", "mean"),
    max_petal_width=("petal_width", "max"),
    std_sepal_width=("sepal_width", "std")
)

group_result


'''create a new column: "petal_ratio"= petal_length/petal_width
For each species, find average petal_ratio 
'''

new_column=df.assign(petal_ratio= df["petal_length"]/df["petal_width"])

new_column.groupby("species")["petal_ratio"].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

In [42]:
'''start by loading  the TITANIC dataset.
A. display only columns: Name, Sex, Age, Fare, Survived
'''

df=pd.read_csv("Titanic-Dataset.csv")
df[["Name", "Sex", "Age", "Fare", "Survived"]]


'''Select passengers who:
i. are females
ii. Fare> 30
'''

df[(df["Sex"]=="female") & (df["Fare"]>30)]


'''Groupby Pclass and compute:
i. Survival rate
ii. Average Fare
iii. Average age
'''

df.groupby("Pclass").agg(
    survival_rate=("Survived","mean"),
    avg_fare=("Fare", "mean"),
    avg_age=("Age", "mean")
)

        survival_rate   avg_fare    avg_age
Pclass
1            0.629630  84.154687  38.233441
2            0.472826  20.662183  29.877630
3            0.242363  13.675550  25.140620

In [35]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q