In [1]:
import pandas as pd
import os

# print(os.getcwd())

# LOAD DATASET

In [2]:
df=pd.read_excel("../data/raw/Online Retail.xlsx")
print(df.head())
print(df.shape)
print(df.columns)
print(df.info())
print(df.ndim)

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
(541909, 8)
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB
None
2

# EXPLORATORY DATA ANALYSES(EDA)

In [5]:
#returns last 5 rows of data

print(df.tail())

       InvoiceNo StockCode                      Description  Quantity  \
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID Country
541904 2011-12-09 12:50:00       0.85     12680.0  France
541905 2011-12-09 12:50:00       2.10     12680.0  France
541906 2011-12-09 12:50:00       4.15     12680.0  France
541907 2011-12-09 12:50:00       4.15     12680.0  France
541908 2011-12-09 12:50:00       4.95     12680.0  France

In [6]:
#give random smaple of data

print(df.sample(5))

       InvoiceNo StockCode                       Description  Quantity  \
135049    547880     21975    PACK OF 60 DINOSAUR CAKE CASES         2
269728    560504     22081        RIBBON REEL FLORA + FAUNA         10
390166    570499     22130  PARTY CONE CHRISTMAS DECORATION         12
22524     538172     79321                     CHILLI LIGHTS         8
43501     540093    35004C   SET OF 3 COLOURED  FLYING DUCKS         2

               InvoiceDate  UnitPrice  CustomerID         Country
135049 2011-03-27 16:05:00       0.55     15426.0  United Kingdom
269728 2011-07-19 11:47:00       1.65     13081.0  United Kingdom
390166 2011-10-11 09:19:00       0.85     12772.0        Portugal
22524  2010-12-10 09:33:00       4.95     15805.0  United Kingdom
43501  2011-01-04 15:24:00       5.45     16725.0  United Kingdom

In [7]:
#returns count of missing values per column

print(df.isnull().sum())

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
#returns TRUE if the dataset contains dupliacte

df.duplicated(["InvoiceNo"])

0         False
1          True
2          True
3          True
4          True
          ...
541904     True
541905     True
541906     True
541907     True
541908     True
Length: 541909, dtype: bool

In [9]:
# count minimum value of quantity

print(df.groupby("InvoiceNo")["Quantity"].min())

print(df["Quantity"].agg(["min", "max", "mean","std"]))

#return row that contains minimum and maximum value because it will outlier for us
print(df.loc[df["Quantity"].agg(["idxmin", "idxmax"])])

InvoiceNo
536365         2
536366         6
536367         2
536368         3
536369         3
           ...
C581484   -80995
C581490      -12
C581499       -1
C581568       -5
C581569       -5
Name: Quantity, Length: 25900, dtype: int64
min    -80995.000000
max     80995.000000
mean        9.552250
std       218.081158
Name: Quantity, dtype: float64
       InvoiceNo StockCode                  Description  Quantity  \
540422   C581484     23843  PAPER CRAFT , LITTLE BIRDIE    -80995
540421    581483     23843  PAPER CRAFT , LITTLE BIRDIE     80995

               InvoiceDate  UnitPrice  CustomerID         Country
540422 2011-12-09 09:27:00       2.08     16446.0  United Kingdom
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom

In [4]:
#how many rows in dataset contains InvoiceNo starts with c and how many rows with c

cancel_transactions=[]
non_cancel_transactions=[]

df["InvoiceNo"]=df["InvoiceNo"].astype(str)

for i in df["InvoiceNo"]:
    if "C" in i:
        cancel_transactions.append(i)
    else:
        non_cancel_transactions.append(i)

cancel_len=len(cancel_transactions)
non_cancel_len=len(non_cancel_transactions)
total_rows=len(df)

print("percentage of cancel transactions:", (cancel_len/total_rows)*100, "%")
print("percentage of non-cancel transactions:", (non_cancel_len/total_rows)*100, "%")

percentage of cancel transactions: 1.7139409015166756 %
percentage of non-cancel transactions: 98.28605909848332 %

In [44]:
# new dataframe for cancel and non_cancel transactions

df["InvoiceNo"]=df["InvoiceNo"].astype(str)

non_cancel_df=df[df["InvoiceNo"].str.fullmatch(r"\d+")].copy()

cancel_df=df[df["InvoiceNo"].str.startswith("C")].copy()
non_cancel_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [41]:
negative_quantity=cancel_df[cancel_df["Quantity"] < 0]

negative_quantity

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [5]:
#EDA on non_cancel_df

non_cancel_df["Quantity"].agg(["min", "max"])

print(non_cancel_df.loc[non_cancel_df["Quantity"].agg(["idxmin", "idxmax"])])

       InvoiceNo StockCode                   Description  Quantity  \
225529    556690     23005  printing smudges/thrown away     -9600
540421    581483     23843   PAPER CRAFT , LITTLE BIRDIE     80995

               InvoiceDate  UnitPrice  CustomerID         Country
225529 2011-06-14 10:37:00       0.00         NaN  United Kingdom
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom

In [55]:
# look at the negative Quantity rows of non-cancel_df

negative_quantity=non_cancel_df[non_cancel_df["Quantity"]< 0]
negative_quantity

#look at the positive quantity rows of non-cancel_df
positive_quantity=non_cancel_df[non_cancel_df["Quantity"]>= 0]
positive_quantity

#new dataframe of negative quantity for EDA
neg_quan_df=non_cancel_df.loc[non_cancel_df["Quantity"] < 0].copy()

#check customer_id in neg_quan_df
check_customerID=neg_quan_df[neg_quan_df["CustomerID"].isnull()]
check_customerID

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
535333,581210,23395,check,-26,2011-12-07 18:36:00,0.0,NaN,United Kingdom
535335,581212,22578,lost,-1050,2011-12-07 18:38:00,0.0,NaN,United Kingdom
535336,581213,22576,check,-30,2011-12-07 18:38:00,0.0,NaN,United Kingdom
536908,581226,23090,missing,-338,2011-12-08 09:56:00,0.0,NaN,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

In [65]:
#non cancel postive quantity make new dataframe
non_cancel_pos_df=non_cancel_df.loc[non_cancel_df["Quantity"]> 0].copy()

print(non_cancel_pos_df["Quantity"].agg(["min", "max"]))
non_cancel_pos_df

min        1
max    80995
Name: Quantity, dtype: int64

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [16]:
#look at customer 16446.0

print(non_cancel_df.loc[non_cancel_df["CustomerID"]==16446.0])

#calculate total money for this transaction
total_money=(
    non_cancel_df.at[540421, "Quantity"]
    *non_cancel_df.at[540421, "UnitPrice"]
)

print("total money:", total_money)

       InvoiceNo StockCode                  Description  Quantity  \
194354    553573     22980       PANTRY SCRUBBING BRUSH         1
194355    553573     22982          PANTRY PASTRY BRUSH         1
540421    581483     23843  PAPER CRAFT , LITTLE BIRDIE     80995

               InvoiceDate  UnitPrice  CustomerID         Country
194354 2011-05-18 09:52:00       1.65     16446.0  United Kingdom
194355 2011-05-18 09:52:00       1.25     16446.0  United Kingdom
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom
total money: 168469.6

In [34]:
print(non_cancel_df.loc[non_cancel_df["StockCode"]==23843])

print(non_cancel_df["Quantity"].nlargest(20))
print(non_cancel_df.loc[61619])
print(non_cancel_df.loc[502122])
print(non_cancel_df.loc[non_cancel_df["CustomerID"]==12346.0])
print("searching in cancel transactions")
print(cancel_df.loc[cancel_df["CustomerID"]==12346.0])
print(cancel_df.loc[cancel_df["StockCode"]==23843])

       InvoiceNo StockCode                  Description  Quantity  \
540421    581483     23843  PAPER CRAFT , LITTLE BIRDIE     80995

               InvoiceDate  UnitPrice  CustomerID         Country
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom
540421    80995
61619     74215
502122    12540
74614      5568
421632     4800
206121     4300
220843     4000
97432      3906
270885     3186
52711      3114
160546     3114
263885     3100
115807     3000
433788     3000
4945       2880
291249     2880
201149     2700
80742      2592
74615      2560
32671      2400
Name: Quantity, dtype: int64
InvoiceNo                              541431
StockCode                               23166
Description    MEDIUM CERAMIC TOP STORAGE JAR
Quantity                                74215
InvoiceDate               2011-01-18 10:01:00
UnitPrice                                1.04
CustomerID                            12346.0
Country                        United Kingdom
Name: 61619, dtype: object
InvoiceNo                              578841
StockCode                               84826
Description    ASSTD DESIGN 3D PAPER STICKERS
Quantity                                12540
InvoiceDate               2011-11-25 15:57:00
UnitPrice                                 0.0
CustomerID                            13256.0
Country                        United Kingdom
Name: 502122, dtype: object
      InvoiceNo StockCode                     Description  Quantity  \
61619    541431     23166  MEDIUM CERAMIC TOP STORAGE JAR     74215

              InvoiceDate  UnitPrice  CustomerID         Country
61619 2011-01-18 10:01:00       1.04     12346.0  United Kingdom
searching in cancel transactions
      InvoiceNo StockCode                     Description  Quantity  \
61624   C541433     23166  MEDIUM CERAMIC TOP STORAGE JAR    -74215

              InvoiceDate  UnitPrice  CustomerID         Country
61624 2011-01-18 10:17:00       1.04     12346.0  United Kingdom
       InvoiceNo StockCode                  Description  Quantity  \
540422   C581484     23843  PAPER CRAFT , LITTLE BIRDIE    -80995

               InvoiceDate  UnitPrice  CustomerID         Country
540422 2011-12-09 09:27:00       2.08     16446.0  United Kingdom
      InvoiceNo StockCode                     Description  Quantity  \
29066   C538702     84826  ASSTD DESIGN 3D PAPER STICKERS       -60

              InvoiceDate  UnitPrice  CustomerID         Country
29066 2010-12-14 10:28:00       0.85     13008.0  United Kingdom